mongo:
  image: mongo
  restart: always
  volumes:
    - database:/data/db
  ports:
    - "27017:27017"

app:
  build: .
  dockerfile: docker/Dockerfile
  ports:
    - "8082:8080"
  links:
    - mongo

#zookeeper:
#  image: zookeeper:latest
#  environment:
#    ZOOKEEPER_CLIENT_PORT: 2181
#    ZOOKEEPER_TICK_TIME: 2000
#    ZOOKEEPER_SYNC_LIMIT: 2
#  ports:
#    - 2181:2181
#kafka:
#  image: wurstmeister/kafka:latest
#  ports:
#    - 9092:9092
#  environment:
#    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    KAFKA_CREATE_TOPICS: "meu-topico-legal:1:1"
#    KAFKA_BROKER_ID: 2
#    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
